name: Auto-Preprocessing-Pipeline
on: [push] # Berjalan tiap kali kamu push kode

jobs:
  preprocess_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Pandas
        run: pip install pandas

      - name: Run Automation Script
        run: python preprocessing/automate_m_haidar.py